#include <iostream>
#ifndef CONSTS_HPP
#define CONSTS_HPP
static const int DEFAULT_PORT = 8000;
static const int BUFFER_SIZE = 30720;

static const std::string TYPE_TEXT = "text/plain";
static const std::string TYPE_HTML = "text/html";
static const std::string TYPE_CSS = "text/css";
static const std::string TYPE_JSON = "application/json";
static const std::string TYPE_XML = "application/xml";
static const std::string TYPE_PDF = "application/pdf";
static const std::string TYPE_JPEG = "image/jpeg";
static const std::string TYPE_PNG = "image/png";
static const std::string TYPE_GIF = "image/gif";
static const std::string TYPE_WEBP = "image/webp";
static const std::string TYPE_MPEG = "audio/mpeg";
static const std::string TYPE_OGG = "audio/ogg";
static const std::string TYPE_MP4 = "video/mp4";
static const std::string TYPE_MPEG_VIDEO = "video/mpeg";
static const std::string TYPE_FORM_DATA = "multipart/form-data";
// Thanks to https://github.com/j-ulrich/http-status-codes-cpp
static const int STATUS_CONTINUE = 100;
static const int STATUS_SWITCHINGPROTOCOLS = 101;
static const int STATUS_PROCESSING = 102;
static const int STATUS_EARLYHINTS = 103;
static const int STATUS_OK = 200;
static const int STATUS_CREATED = 201;
static const int STATUS_ACCEPTED = 202;
static const int STATUS_NONAUTHORITATIVEINFORMATION = 203;
static const int STATUS_NOCONTENT = 204;
static const int STATUS_RESETCONTENT = 205;
static const int STATUS_PARTIALCONTENT = 206;
static const int STATUS_MULTISTATUS = 207;
static const int STATUS_ALREADYREPORTED = 208;
static const int STATUS_IMUSED = 226;
static const int STATUS_MULTIPLECHOICES = 300;
static const int STATUS_MOVEDPERMANENTLY = 301;
static const int STATUS_FOUND = 302;
static const int STATUS_SEEOTHER = 303;
static const int STATUS_NOTMODIFIED = 304;
static const int STATUS_USEPROXY = 305;
static const int STATUS_TEMPORARYREDIRECT = 307;
static const int STATUS_PERMANENTREDIRECT = 308;
static const int STATUS_BADREQUEST = 400;
static const int STATUS_UNAUTHORIZED = 401;
static const int STATUS_PAYMENTREQUIRED = 402;
static const int STATUS_FORBIDDEN = 403;
static const int STATUS_NOTFOUND = 404;
static const int STATUS_METHODNOTALLOWED = 405;
static const int STATUS_NOTACCEPTABLE = 406;
static const int STATUS_PROXYAUTHENTICATIONREQUIRED = 407;
static const int STATUS_REQUESTTIMEOUT = 408;
static const int STATUS_CONFLICT = 409;
static const int STATUS_GONE = 410;
static const int STATUS_LENGTHREQUIRED = 411;
static const int STATUS_PRECONDITIONFAILED = 412;
static const int STATUS_CONTENTTOOLARGE = 413;
static const int STATUS_PAYLOADTOOLARGE = 413;
static const int STATUS_URITOOLONG = 414;
static const int STATUS_UNSUPPORTEDMEDIATYPE = 415;
static const int STATUS_RANGENOTSATISFIABLE = 416;
static const int STATUS_EXPECTATIONFAILED = 417;
static const int STATUS_IMATEAPOT = 418;
static const int STATUS_MISDIRECTEDREQUEST = 421;
static const int STATUS_UNPROCESSABLECONTENT = 422;
static const int STATUS_UNPROCESSABLEENTITY = 422;
static const int STATUS_LOCKED = 423;
static const int STATUS_FAILEDDEPENDENCY = 424;
static const int STATUS_TOOEARLY = 425;
static const int STATUS_UPGRADEREQUIRED = 426;
static const int STATUS_PRECONDITIONREQUIRED = 428;
static const int STATUS_TOOMANYREQUESTS = 429;
static const int STATUS_REQUESTHEADERFIELDSTOOLARGE = 431;
static const int STATUS_UNAVAILABLEFORLEGALREASONS = 451;
static const int STATUS_INTERNALSERVERERROR = 500;
static const int STATUS_NOTIMPLEMENTED = 501;
static const int STATUS_BADGATEWAY = 502;
static const int STATUS_SERVICEUNAVAILABLE = 503;
static const int STATUS_GATEWAYTIMEOUT = 504;
static const int STATUS_HTTPVERSIONNOTSUPPORTED = 505;
static const int STATUS_VARIANTALSONEGOTIATES = 506;
static const int STATUS_INSUFFICIENTSTORAGE = 507;
static const int STATUS_LOOPDETECTED = 508;
static const int STATUS_NOTEXTENDED = 510;
static const int STATUS_NETWORKAUTHENTICATIONREQUIRED = 511;

std::string statusText(int status);
std::string methodText(int method);
#endif
